version: "3.9"

services:
  database:
    container_name: database
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./api/.env
    networks:
      - bravi
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    container_name: bravi-api
    ports:
      - 8000:8000
    build: ./api
    depends_on:
      database:
        condition: service_healthy
    networks:
      - bravi
    restart: always

networks:
  bravi:
